### ISSUE TITLE
Suggested compliments for the cute bot

### ISSUE THREAD

**Issue by doloresonthedot** [rachelnicole/isReallyCute-bot#4]
You are as radiant as the sun 
When you smile all the stars in the sky light up 
Your cuteness makes puppies jealous
You brighten everyone's day 
You're a cutie, please never stop the cuteness
You're adorable 
When I look at you everything else fades into the background 
You're cute and deserve happiness and love and joy 
You brighten my day 
You have a delightful face
You have a delightful smile 
You delight me 
Everything about you is rather cute 
Looking at you is a breath of fresh air 
I can feel your cuteness from here 
You look really nice today and every day 
Your QTness brightens my day 
Looking at you is like wrapping myself in warm blankets 
You're the best version of yourself that you can be 
What lovely hair you have
I appreciate all of you 
I like your style cutie 
You're so charming 
How do you get your hair to look so great? 
Even the moon agrees that you're the cutest

**Comment by rachelnicole** [comment]
These are great! I'll add them in tonight. :D

**Comment by rachelnicole** [comment]
@doloresonthedot i am a slow jerk, but i added these in today and I'm rebuilding the bot tonight so it works again. Thank you SO much and I'm sorry it took me so long.
